### ISSUE TITLE
A small issue for asking.

### ISSUE THREAD

**Issue by darkmir** [Caoliangjie/pytorch-gradcam-resnet50#1]
After running the code under the command, the issue returns:
cv.error: Opencv(4.0.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:3784 : error: (-215:Assertion failed) !ssize.empty() in function 'cv:resize'
How can I fix it then? 
Best regards!

**Comment by Caoliangjie** [comment]
> After running the code under the command, the issue returns:
> cv.error: Opencv(4.0.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:3784 : error: (-215:Assertion failed) !ssize.empty() in function 'cv:resize'
> How can I fix it then?
> Best regards!

Hi，darkmir,I think you got the wrong path to read image. You should check the image path whether it's wrong or correct.

**Comment by darkmir** [comment]
Thx for replying. With higher version opencv, it's really harder to ascertain the bug.
After reinstall opencv 3.4 version, the issue has been fixed.
Thx for your generous help!
