### ISSUE TITLE
why the target_index variable is invalid in your code?

### ISSUE THREAD

**Issue by muyiguangda** [Caoliangjie/pytorch-gradcam-resnet50#10]
change the target_index number in main function, it's no difference for the cam mask. It mains we can only check the highest score category, or something wrong?

**Comment by Caoliangjie** [comment]
Hi muyiguangda, you can change to the deeper layer to see the diffences, it really works. Here's two pitures for example.(1 is set index to 100, 2 is None)
![image](https://user-images.githubusercontent.com/38064559/65222667-1e7d9c00-daf2-11e9-878b-3a9715910f00.png)
![image](https://user-images.githubusercontent.com/38064559/65222743-4bca4a00-daf2-11e9-93ee-107bc8bbc8aa.png)
Maybe this can help you.
