### ISSUE TITLE
关于self.model.zero_grad()

### ISSUE THREAD

**Issue by zhouyongxiu** [Caoliangjie/pytorch-gradcam-resnet50#2]
我对比了一下原版的代码，你将原本的
self.model.features.zero_grad()
self.model.classifier.zero_grad()
改成了
self.model.zero_grad()
self.model.zero_grad()
请问一下1.为什么要这么修改。2.两行代码是否重复了。

**Comment by Caoliangjie** [comment]
你好,关于问题1首先这个是因为预训练模型本身包含的参数这么设定的,vgg的预训练模型是包含features和classifier两个子类的,但是resnet50里面没有这么写,这个我后面注释里也写到了,加进去会报错的,可以改回去验证一下.
问题2的话,其实整体来讲不影响,毕竟是把梯度全部清空了,而且导入的model类实际上也是不包含classifier的.最后我们也不会用fc层进行操作.多打这一句当时只是为了把.classfier那一块和features一起说明,总体来说不影响使用,但是确实对于严谨性上需要改正,已修改,感谢指正.

**Comment by zhouyongxiu** [comment]
@Caoliangjie 非常感谢你的耐心解答，另外还有一个想请教一下，代码里的GuidedBackpropReLU和GuidedBackpropReLUModel这两个类好像并没有被调用，请问一下这两个类原本实现什么功能，是否可以删掉。

**Comment by Caoliangjie** [comment]
你好,这两个类对cam图打印是没什么影响的,下面我也把对应的代码注释掉了.具体功能我也没有仔细研究,感兴趣的话可以自己操作看一看具体打印出来是什么效果.

**Comment by zhouyongxiu** [comment]
@Caoliangjie 谢谢
