### ISSUE TITLE
关于视频的gradcam

### ISSUE THREAD

**Issue by emily19941102** [Caoliangjie/pytorch-gradcam-resnet50#3]
您好，我也是做视频的，请问你做出来了吗？x谢谢
@Caoliangjie

**Comment by Caoliangjie** [comment]
您好,这个做的话其实还是挺简单的,不过我目前暂时没有精力维护这一块,大概下个月会抽空嵌入一个3d的网络试试看.
您可以尝试做一做,建议是把gradcam这个类读一下,然后理解对应3d网络的结构,实际上我们只是对同一时间维度上的多张图一块做这个操作而已.
如果还是无法理解的话,可以先把自己拆好的帧存下来之后用自己的网络修改跑一下这段代码.中间过程处理和后处理都是可以做的.
再不然..就看我这边什么时候忙完吧...毕竟我也不是个高技术力人....入坑也不久而已

**Comment by emily19941102** [comment]
太感谢了！辛苦你码这么多字了！我接下来尝试一下，感谢你的建议！------------------ 原始邮件 ------------------
发件人: "Simon"<notifications@github.com>
发送时间: 2019年4月24日(星期三) 中午12:01
收件人: "Caoliangjie/pytorch-gradcam-resnet50"<pytorch-gradcam-resnet50@noreply.github.com>;
抄送: "emily19941102"<997296801@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Caoliangjie/pytorch-gradcam-resnet50] 关于视频的gradcam (#3)



您好,这个做的话其实还是挺简单的,不过我目前暂时没有精力维护这一块,大概下个月会抽空嵌入一个3d的网络试试看.
 您可以尝试做一做,建议是把gradcam这个类读一下,然后理解对应3d网络的结构,实际上我们只是对同一时间维度上的多张图一块做这个操作而已.
 如果还是无法理解的话,可以先把自己拆好的帧存下来之后用自己的网络修改跑一下这段代码.中间过程处理和后处理都是可以做的.
 再不然..就看我这边什么时候忙完吧...毕竟我也不是个高技术力人....入坑也不久而已
 
&mdash;

**Comment by Caoliangjie** [comment]
好的,加油
