### ISSUE TITLE
代码解释

### ISSUE THREAD

**Issue by Captainzj** [Caoliangjie/pytorch-gradcam-resnet50#4]
https://github.com/Caoliangjie/pytorch-gradcam-resnet50/blob/master/grad-cam.py　＃28
`for name, module in self.model._modules.items():##resnet50没有.feature这个特征，直接删除用就可以。`

具体是删除哪些呢？

**Comment by Caoliangjie** [comment]
你好，我这个已经是把.feature给删除了，本来原工程是基于vgg16的网络改的，那个工程比较老了，resnet模型里不带.feature这个子类。这段代码可以直接用的，不需要自己改，不懂得地方可以对照原始工程compare diff看一下。
