### ISSUE TITLE
our own network

### ISSUE THREAD

**Issue by ilovekj** [Caoliangjie/pytorch-gradcam-resnet50#5]
excuse me, can you tell me how to get gradcam with my own networks?

**Comment by Caoliangjie** [comment]
Hello, if you don't want to spend many time, I think firstly you  can save your own model as .pth files, then you can load your own network suit for this project. In fact, this project can only suit for your own network  by this method, it's suit for the validation process. So firstly try to save your own network as .pth files by using `torch.save('xxx.pth',x)` to get the model file.

**Comment by ilovekj** [comment]
@Caoliangjie thank you a lot, I am successful to get cam image on my own networks when i did image classification, however, when i tried to get cam image on video action recognization networks, which includes several frames, there are Something wrong, could you help me ?

**Comment by Caoliangjie** [comment]
Hello, actually you can read my `README.md` file, I think this project is just compose the extract features and the origin clips. So that means if you can extract the features by using your own network from the origin clips and then compose them, the outcome is the same. You can firstly get the features from which layer you want to get then select the best features composed with the origin clips.
If you still don't know how to solve this problem, after my work have done, I will try to solve this problem. Best wishes!

**Comment by ilovekj** [comment]
hello， thank you for your reply, I notice the code:"
		cam = cv2.resize(cam, (224, 224))", when we  use clips, we have trouble reshaping like this

**Comment by ilovekj** [comment]
can you tell me how to solve this problem, I am to resolve it by myself, thank you

**Comment by Caoliangjie** [comment]
> can you tell me how to solve this problem, I am to resolve it by myself, thank you
Hello, as for this problem, I think you may have some misunderstanding for this question.  This is just a  step for resize the cam image from its origin size to (224,224). You can print the size before the resize step. You should remember the features you have extract is not the same size as the origin image. I think you firstly should realize the conception of extracting features from one image. After that, you will have a clear mind to solve this problem. You should know that frames is like a tuple with many images. So if you can process one image, more images you can process as well.
By the way, you should strengthen your written English. Best wishes!

**Comment by Caoliangjie** [comment]
> can you tell me how to solve this problem, I am to resolve it by myself, thank you

Hello, as for this problem, I think you may have some misunderstanding for this question.  This is just a  step for resize the cam image from its origin size to (224,224). You can print the size before the resize step. You should remember the features you have extract is not the same size as the origin image. I think you firstly should realize the conception of extracting features from one image. After that, you will have a clear mind to solve this problem. You should know that frames is like a tuple with many images. So if you can process one image, more images you can process as well.
By the way, you should strengthen your written English. Best wishes!

**Comment by ilovekj** [comment]
算了，看来我怎么努力也描述不清楚，在视频处理中，在时间维度的长度也减少了，你需要吧feature马匹、上计算的cam分数叠加到原图去，是很难缩放回去的

**Comment by ilovekj** [comment]
我英语写作的确很久没学了，多谢提醒

**Comment by Caoliangjie** [comment]
> 我英语写作的确很久没学了，多谢提醒

你好，在readme里我有写到，实际上只需要解决提取feature这一步核心，后面就很好做了。可以这么想，经过卷积层的时候你原始的数据实际上就是从多通道变为另一个多通道的数据，卷积卷积，说白了是把卷积核确定好之后在不同尺度上对这个图像也好视频帧也好都会做这么一步处理。一般我们提取特征也就是从这里提取得到，对于你的疑惑，可以先尝试将每个通道的特征都打印出来理解一下feature的概念。
至于关于叠加到原图的疑惑，这一点在readme中也有说道，最后他只是做了一步叠加到原图罢了。对于视频处理而言确实是由于时间维度仍有n次卷积也会变化，因此不是说直接生硬的保证最后所有的feature都能够映射到对应的图，这一点你确实没有理解错。所以这也正是我在readme中说到的最后可以依靠opencv乃至ps将得到的最理想的特征与对应的原图拼合，就可以达到一样的效果。也可以直接套用里面的show_cam_on_image函数的样式做出来，只是要保证尺度一致。
解答有所不周全的地方或者没有理解的地方，请包涵。同为初学者，有不懂的还要互相请教。

**Comment by ilovekj** [comment]
我能加您微信吗？我还有好多问题想请教

**Comment by Caoliangjie** [comment]
> 我能加您微信吗？我还有好多问题想请教

你好，我也只是个入门不久的小萌新，请教谈不上，只能说是互相学习。

**Comment by ilovekj** [comment]
没事，那加个好友呗

**Comment by Caoliangjie** [comment]
> 没事，那加个好友呗

你好，我的微信二维码已经发到你的邮箱了，互相学习进步。

**Comment by ilovekj** [comment]
您好，我好像没收到您的二维码

**Comment by chenbolinstudent** [comment]
您好 ，可以加我qq 吗 2549853330

**Comment by swg209** [comment]
@Caoliangjie  您好， 我的模型是在以resnet50 layer1-4为骨干， 去掉了fc层， 然后接了一个gap全局池化，在接了一层fc(2048,512), 最后接分类fc层。我参考您的做法，在可视化模型layer4的时候，出现的效果是这样子的，
![image](https://user-images.githubusercontent.com/19169247/74412262-f8c5aa80-4e77-11ea-9e40-85b05f6bb626.png)
请问您知道是什么原因吗？
